
services:
  postgres:
    image: postgres:14
    container_name: postgres-flexxus
    restart: always
    environment:
      POSTGRES_USER: flexxus_user
      POSTGRES_PASSWORD: flexxus_pass
      POSTGRES_DB: prueba_flexxus
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
